'use client';

import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, LoaderCircle, Shield, UserRound, UserX } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { formatArticleDateTime } from '@/lib/formatters';

type AdminUser = { id: number; username: string; display_name: string | null; bio: string | null; role: 'user' | 'admin'; is_active: number; created_at: string };
const backendUrl = process.env.NEXT_PUBLIC_BACKEND_API_URL || 'http://localhost:8787';

export default function AdminUsersPage() {
  const { token, user: currentUser } = useAuth();
  const [users, setUsers] = useState<AdminUser[]>([]); const [isLoading, setIsLoading] = useState(true); const [busyId, setBusyId] = useState<number | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!token) return; setIsLoading(true); setError(null); try { const response = await fetch(`${backendUrl}/api/users`, { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.error || '获取用户列表失败'); setUsers(data.items || []); } catch (reason) { setError(reason instanceof Error ? reason.message : '获取用户列表失败'); } finally { setIsLoading(false); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  const update = async (id: number, changes: Partial<Pick<AdminUser, 'role' | 'is_active'>>) => { if (!token) return; setBusyId(id); try { const response = await fetch(`${backendUrl}/api/users/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(changes) }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.error || '用户更新失败'); setUsers((items) => items.map((item) => item.id === id ? data : item)); } catch (reason) { setError(reason instanceof Error ? reason.message : '用户更新失败'); } finally { setBusyId(null); } };
  return <section><div><h2 className="text-2xl font-bold text-slate-950">用户管理</h2><p className="mt-2 text-sm text-slate-500">可以停用异常账号或调整其他用户的管理员权限；当前登录管理员不可在这里修改自己。</p></div>{error && <p role="alert" className="mt-4 rounded-control border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</p>}<div className="surface-card mt-6 overflow-hidden">{isLoading ? <div className="flex min-h-48 items-center justify-center gap-2 text-sm text-slate-500"><LoaderCircle className="size-4 animate-spin" />正在加载用户...</div> : users.length === 0 ? <p className="py-14 text-center text-sm text-slate-500">暂无注册用户。</p> : <ul className="divide-y divide-slate-100">{users.map((account) => { const isCurrent = String(account.id) === currentUser?.id; return <li key={account.id} className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="flex min-w-0 items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-control bg-slate-100 text-slate-600">{account.role === 'admin' ? <Shield className="size-5" /> : <UserRound className="size-5" />}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="truncate text-slate-900">{account.display_name || account.username}</strong><span className="text-sm text-slate-400">@{account.username}</span>{account.role === 'admin' && <span className="rounded-full bg-violet-50 px-2 py-0.5 text-xs text-violet-700">管理员</span>}{account.is_active === 0 && <span className="rounded-full bg-rose-50 px-2 py-0.5 text-xs text-rose-700">已停用</span>}</div><p className="mt-1 text-xs text-slate-400">注册于 {formatArticleDateTime(account.created_at)}</p></div></div><div className="flex flex-wrap gap-2">{isCurrent ? <span className="inline-flex h-9 items-center rounded-control bg-slate-100 px-3 text-xs text-slate-500">当前账户</span> : <><button disabled={busyId === account.id} type="button" onClick={() => void update(account.id, { is_active: account.is_active ? 0 : 1 })} className={`inline-flex h-9 items-center gap-1.5 rounded-control px-3 text-sm font-medium disabled:opacity-50 ${account.is_active ? 'border border-rose-200 text-rose-700 hover:bg-rose-50' : 'border border-emerald-200 text-emerald-700 hover:bg-emerald-50'}`}>{account.is_active ? <UserX className="size-4" /> : <CheckCircle2 className="size-4" />}{account.is_active ? '停用' : '启用'}</button><button disabled={busyId === account.id} type="button" onClick={() => void update(account.id, { role: account.role === 'admin' ? 'user' : 'admin' })} className="inline-flex h-9 items-center gap-1.5 rounded-control border border-slate-200 px-3 text-sm font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50"><Shield className="size-4" />{account.role === 'admin' ? '撤销管理' : '设为管理员'}</button></>}</div></li>; })}</ul>}</div></section>;
}
