name = "jiazhuangai2vs"
compatibility_date = "2024-09-23" # 请确保这个日期与您 Cloudflare Pages UI 中的兼容日期一致或更新
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./frontend/.vercel/output/static" # 确保 Pages 读取此文件