name = "jiazhuangai-backend" # Worker 名称
main = "src/index.ts" # 入口文件 (稍后创建)
compatibility_date = "2024-05-30" # 使用当前日期或根据需要调整

# 确保Workers在全球都可访问
[placement]
mode = "smart" # 智能路由，自动选择最佳数据中心

# [vars] 部分用于定义环境变量
# 这些变量在本地开发 (wrangler dev) 时可用
# 在生产环境中，您需要在 Cloudflare Dashboard 中设置这些变量
[vars]
# 重要：请将下面的 JWT_SECRET 替换为一个长而随机的、安全的字符串！
# 例如，您可以使用 openssl rand -hex 32 来生成一个。
JWT_SECRET = "replace-this-with-your-actual-strong-secret-key-that-is-at-least-32-characters-long"

# Routes configuration
routes = [
    { pattern = "api.jiazhuangai.com/*", zone_name = "jiazhuangai.com" }
]

# KV Namespace binding
[[kv_namespaces]]
binding = "KV"
id = "a120d00a55da47e682ad94852b8ab4cb"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "jiazhuangai"
database_id = "69c4b792-fca3-48f6-a280-1c9977ed1dee"

# R2 Bucket binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "jiazhuangai-files"